allowBuilds:
  automata-user-management: true
  automata-cache: true
  automata-db: true
  automata-utils: true

  bcrypt: true
  better-sqlite3: true
  unrs-resolver: true

blockExoticSubdeps: false
